#lang info
(define collection "drracket-hicontrast")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define pkg-desc "A high-contrast theme for DrRacket")
(define version "1")
(define pkg-authors '(jimpjorps))
(define license '(MIT))

(define framework:color-schemes
  '(#hash((white-on-black-base? . #t)
          (colors . ((drracket:syncheck:template-arrow #(218 112 214))
                     (plt:module-language:test-coverage-off #(255 120 118))
                     (drracket:check-syntax:both-obligation-style-pref #(0 255 255))
                     (drracket:syncheck:matching-identifiers #(0 100 0))
                     (framework:syntax-color:scheme:parenthesis #(192 192 192) normal bold)
                     (drracket:syncheck:untacked #(255 255 255))
                     (drracket:check-syntax:lexically-bound #(0 255 64))
                     (drracket:check-syntax:free-variable #(255 128 0))
                     (framework:paren-match-color #(0 0 128))
                     (framework:line-numbers #(211 211 211))
                     (drracket:check-syntax:unused-require #(255 128 0))
                     (framework:misspelled-text-color #(255 0 0))
                     (framework:default-text-color #(250 250 240))
                     (framework:line-numbers-current-line-number-foreground #(0 0 0))
                     (stepper:error-color #(255 0 0))
                     (drracket:syncheck:tail-arrow #(218 112 214))
                     (framework:syntax-color:scheme:symbol #(255 255 255) normal normal)
                     (framework:syntax-color:scheme:text #(0 255 255) normal normal)
                     (drracket:syncheck:var-arrow #(176 196 222))
                     (framework:warning-background-color #(155 135 12))
                     (drracket:check-syntax:unk-obligation-style-pref #(255 255 255))
                     (framework:program-contour-current-location-bar #(93 104 158))
                     (drracket:check-syntax:my-obligation-style-pref #(255 128 0))
                     (framework:disabled-background-color #(105 105 105))
                     (framework:syntax-color:scheme:hash-colon-keyword #(128 255 255) italic)
                     (drracket:check-syntax:set!d #(255 128 0))
                     (stepper:arrow-color #(255 0 0))
                     (stepper:redex-highlight-color #(67 122 55))
                     (framework:syntax-color:scheme:keyword #(255 0 0) normal bold)
                     (framework:basic-canvas-background #(0 0 0))
                     (drracket:syncheck:document-identifier #(0 100 0))
                     (drracket:language-name-and-memory-use-at-top-of-interactions #(152 251 152))
                     (drracket:read-eval-print-loop:error-color #(255 128 0) italic)
                     (stepper:reduct-highlight-color #(135 81 168))
                     (framework:syntax-color:scheme:string #(255 255 0))
                     (framework:syntax-color:scheme:comment #(192 192 192))
                     (plt:htdp:test-coverage-off #(255 255 255) normal normal)
                     (drracket:read-eval-print-loop:out-color #(0 255 255))
                     (framework:line-numbers-current-line-number-background #(108 186 112))
                     (drracket:syncheck:unused-identifier #(178 34 34))
                     (drracket:read-eval-print-loop:value-color #(255 255 255))
                     (plt:module-language:test-coverage-on #(255 255 255))
                     (plt:htdp:test-coverage-on #(255 255 255))
                     (framework:syntax-color:scheme:other #(255 128 0))
                     (framework:failed-search-background-color #(178 34 34))
                     (drracket:check-syntax:imported #(255 128 0))
                     (drracket:check-syntax:their-obligation-style-pref #(0 255 0))
                     (framework:syntax-color:scheme:error #(255 0 0) italic normal)
                     (drracket:error-background-highlighting #(117 0 0))
                     (framework:line-numbers-when-word-wrapping #(169 169 169))
                     (framework:syntax-color:scheme:constant #(128 255 0) normal)))
          (name . "High contrast"))))
